-- BD GESTOR DE PEDIDOS
-- Ejercicio asignado: 17
-- Base de datos: Supabase PostgreSQL
-- Creador: Neider Lizcano


-- NOTA: Debido a las funcionalidades de Supabase, la contraseña del usuario es
-- administrada por Supabase Authentication y no se almacena directamente en
-- la tabla public.usuarios.


CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    username TEXT NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);


CREATE UNIQUE INDEX IF NOT EXISTS usuarios_username_unique_ci
ON public.usuarios (LOWER(BTRIM(username)));


CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario_id UUID NOT NULL
        DEFAULT auth.uid()
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    fecha DATE NOT NULL,
    fecha_envio DATE,
    fecha_entrega DATE,

    cliente TEXT NOT NULL,
    proveedor TEXT NOT NULL,

    valor NUMERIC NOT NULL,
    estado TEXT NOT NULL,

    pais TEXT NOT NULL,
    departamento TEXT NOT NULL,
    ciudad TEXT NOT NULL,
    nomenclatura_vivienda TEXT NOT NULL,

    propina NUMERIC NOT NULL DEFAULT 0
);


ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;


GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.usuarios
TO authenticated;


DROP POLICY IF EXISTS usuarios_select_own
ON public.usuarios;

CREATE POLICY usuarios_select_own
ON public.usuarios
FOR SELECT
TO authenticated
USING (
    (SELECT auth.uid()) = id
);


DROP POLICY IF EXISTS usuarios_insert_own
ON public.usuarios;

CREATE POLICY usuarios_insert_own
ON public.usuarios
FOR INSERT
TO authenticated
WITH CHECK (
    (SELECT auth.uid()) = id
);


DROP POLICY IF EXISTS usuarios_update_own
ON public.usuarios;

CREATE POLICY usuarios_update_own
ON public.usuarios
FOR UPDATE
TO authenticated
USING (
    (SELECT auth.uid()) = id
)
WITH CHECK (
    (SELECT auth.uid()) = id
);


DROP POLICY IF EXISTS usuarios_delete_own
ON public.usuarios;

CREATE POLICY usuarios_delete_own
ON public.usuarios
FOR DELETE
TO authenticated
USING (
    (SELECT auth.uid()) = id
);


CREATE OR REPLACE FUNCTION public.username_disponible(
    p_username TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT NOT EXISTS (
        SELECT 1
        FROM public.usuarios
        WHERE LOWER(BTRIM(username))
            = LOWER(BTRIM(p_username))
    );
$$;


REVOKE ALL
ON FUNCTION public.username_disponible(TEXT)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.username_disponible(TEXT)
TO anon, authenticated;