-- BD GESTOR DE PEDIDOS
-- Ejercicio asignado: 17
-- Base de datos: Supabase PostgreSQL
-- Creador: Neider Lizcano


-- NOTA: Debido a las funcionalidades de Supabase, la contraseña del usuario es
-- administrada por Supabase Authentication y no se almacena directamente en
-- la tabla public.usuarios.


CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    username TEXT NOT NULL,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);


create table if not exists public.pedidos (
    id bigint generated by default as identity primary key,
    usuario_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    fecha date not null,
    fecha_envio date not null,
    fecha_entrega date not null,
    cliente text not null,
    proveedor text not null,
    valor numeric(12,2) not null check (valor > 0),
    estado text not null,
    pais text not null,
    departamento text not null,
    ciudad text not null,
    nomenclatura_vivienda text not null,
    propina numeric(12,2) not null default 0 check (propina >= 0),
    constraint chk_fecha_envio
        check (fecha_envio >= fecha),
    constraint chk_fecha_entrega
        check (fecha_entrega >= fecha_envio)
);

alter table public.usuarios enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "usuarios_select_own" on public.usuarios;
drop policy if exists "usuarios_insert_own" on public.usuarios;
drop policy if exists "usuarios_update_own" on public.usuarios;
drop policy if exists "usuarios_delete_own" on public.usuarios;

create policy "usuarios_select_own"
on public.usuarios
for select
to authenticated
using (id = auth.uid());

create policy "usuarios_insert_own"
on public.usuarios
for insert
to authenticated
with check (id = auth.uid());

create policy "usuarios_update_own"
on public.usuarios
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "usuarios_delete_own"
on public.usuarios
for delete
to authenticated
using (id = auth.uid());

drop policy if exists "pedidos_select_own" on public.pedidos;
drop policy if exists "pedidos_insert_own" on public.pedidos;
drop policy if exists "pedidos_update_own" on public.pedidos;
drop policy if exists "pedidos_delete_own" on public.pedidos;

create policy "pedidos_select_own"
on public.pedidos
for select
to authenticated
using (usuario_id = auth.uid());

create policy "pedidos_insert_own"
on public.pedidos
for insert
to authenticated
with check (usuario_id = auth.uid());

create policy "pedidos_update_own"
on public.pedidos
for update
to authenticated
using (usuario_id = auth.uid())
with check (usuario_id = auth.uid());

create policy "pedidos_delete_own"
on public.pedidos
for delete
to authenticated
using (usuario_id = auth.uid());

create index if not exists idx_pedidos_usuario_id
on public.pedidos(usuario_id);

create index if not exists idx_pedidos_estado
on public.pedidos(estado);

create index if not exists idx_pedidos_ciudad
on public.pedidos(ciudad);

create index if not exists idx_pedidos_fecha
on public.pedidos(fecha);

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from auth.users
    where id = auth.uid();
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;