-- BD GESTOR DE PEDIDOS
-- Ejercicio asignado: 17
-- Base de datos: Supabase PostgreSQL
-- Creador: Neider Lizcano


-- TABLA USUARIOS
-- NOTA:Debido a las funcionalidades de Supabase, la contraseña del usuario es 
-- administrada por Supabase Authentication y no se almacena directamente en 
-- la tabla public.usuarios.

CREATE TABLE public.usuarios (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    username TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);


-- TABLA PEDIDOS
CREATE TABLE public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fecha DATE NOT NULL,
    fecha_envio DATE,
    fecha_entrega DATE,

    cliente TEXT NOT NULL,
    proveedor TEXT NOT NULL,

    valor NUMERIC NOT NULL,
    estado TEXT NOT NULL,

    pais TEXT NOT NULL,
    departamento TEXT NOT NULL,
    ciudad TEXT NOT NULL,
    nomenclatura_vivienda TEXT NOT NULL,

    propina NUMERIC NOT NULL DEFAULT 0
);


-- SEGURIDAD A NIVEL DE FILA
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;